-- MySQL Script generated by MySQL Workbench
-- Tue Mar  2 23:30:15 2021
-- Model: New Model    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patients Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients Table` (
  `Patient ID` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Phone Number` BIGINT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(10) NULL,
  PRIMARY KEY (`Patient ID`),
  UNIQUE INDEX `Patient ID_UNIQUE` (`Patient ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctors table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctors table` (
  `Username` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointments Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointments Table` (
  `Appointment ID` INT NOT NULL,
  `Patient ID` VARCHAR(10) NOT NULL,
  `Username` VARCHAR(10) NOT NULL,
  `Notes` MEDIUMTEXT NULL,
  `Prescription` MEDIUMTEXT NULL,
  `Dat` DATE NOT NULL,
  PRIMARY KEY (`Appointment ID`),
  UNIQUE INDEX `Appointment ID_UNIQUE` (`Appointment ID` ASC) VISIBLE,
  INDEX `fk_Appointments Table_Patients Table_idx` (`Patient ID` ASC) VISIBLE,
  INDEX `fk_Appointments Table_Doctors table1_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_Appointments Table_Patients Table`
    FOREIGN KEY (`Patient ID`)
    REFERENCES `mydb`.`Patients Table` (`Patient ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointments Table_Doctors table1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`Doctors table` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Messages Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Messages Table` (
  `Message ID` INT NOT NULL,
  `Username` VARCHAR(10) NOT NULL,
  `Message` MEDIUMTEXT NOT NULL,
  `Date` VARCHAR(45) NOT NULL,
  `Username & Patient ID` VARCHAR(45) NOT NULL,
  `Seen?` VARCHAR(1) NULL,
  PRIMARY KEY (`Message ID`),
  UNIQUE INDEX `Message ID_UNIQUE` (`Message ID` ASC) VISIBLE,
  INDEX `fk_Messages Table_Doctors table1_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_Messages Table_Doctors table1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`Doctors table` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Logs Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logs Table` (
  `Log ID` INT NOT NULL,
  `Username` VARCHAR(10) NOT NULL,
  `Accessed` MEDIUMTEXT NOT NULL,
  `Date & Time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Log ID`),
  UNIQUE INDEX `Log ID ID_UNIQUE` (`Log ID` ASC) VISIBLE,
  INDEX `fk_Logs Table_Doctors table1_idx` (`Username` ASC) VISIBLE,
  CONSTRAINT `fk_Logs Table_Doctors table1`
    FOREIGN KEY (`Username`)
    REFERENCES `mydb`.`Doctors table` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Patients Table`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;

INSERT INTO `mydb`.`Patients Table` (`Patient ID`, `Name`, `Surname`, `Phone Number`, `Address`, `Username`) VALUES ('jwh01', 'Jamie', 'White', 07578777221, 'CT2 2DB', 'hhac01');
INSERT INTO `mydb`.`Patients Table` (`Patient ID`, `Name`, `Surname`, `Phone Number`, `Address`, `Username`) VALUES ('tjo01', 'Tim', 'Jones', 01122233344, 'BR8 1LK', 'hhac01');
INSERT INTO `mydb`.`Patients Table` (`Patient ID`, `Name`, `Surname`, `Phone Number`, `Address`, `Username`) VALUES ('jpi01', 'Jean', 'Picard', 22233344455, 'US8 1SE', 'tje01');

INSERT INTO `mydb`.`Doctors Table` (`Username`, `Name`, `Surname`, `Password`) VALUES ('hhac01', 'Harry', 'Hacker', '123');
INSERT INTO `mydb`.`Doctors Table` (`Username`, `Name`, `Surname`, `Password`) VALUES ('tje01', 'Tom', 'Jerry', '234');
INSERT INTO `mydb`.`Doctors Table` (`Username`, `Name`, `Surname`, `Password`) VALUES ('jsc01', 'Jack', 'Scone', '345');
INSERT INTO `mydb`.`Doctors Table` (`Username`, `Name`, `Surname`, `Password`) VALUES ('System', 'System', 'System', '1337');

INSERT INTO `mydb`.`Messages Table` (`Message ID`, `Username`, `Message`, `Date`, `Username & Patient ID`) VALUES (0, 'tje01', 'Test: Checking message recieved', '02/04/2021', 'hhac01');
INSERT INTO `mydb`.`Messages Table` (`Message ID`, `Username`, `Message`, `Date`, `Username & Patient ID`) VALUES (1, 'hhac01', 'Test: Checking messages sent arent recieved to sender', '21/02/2021', 'tje01');
INSERT INTO `mydb`.`Messages Table` (`Message ID`, `Username`, `Message`, `Date`, `Username & Patient ID`, `Seen?`) VALUES (2, 'tje01', 'Test: Checking if a message seen in main inbox is seen on welcome page', '01/01/2021', 'hhac01','x');

INSERT INTO `mydb`.`Appointments Table` (`Appointment ID`, `Patient ID`, `Username`, `Notes`, `Prescription`, `Dat`) VALUES (0, 'jwh01', 'hhac01', 'Back hurts all day','Pain Killers', '2021-03-04');
INSERT INTO `mydb`.`Appointments Table` (`Appointment ID`, `Patient ID`, `Username`, `Notes`, `Prescription`, `Dat`) VALUES (1, 'tjo01', 'hhac01', 'Never Showed', '','2021-03-04');
INSERT INTO `mydb`.`Appointments Table` (`Appointment ID`, `Patient ID`, `Username`, `Notes`, `Prescription`, `Dat`) VALUES (2, 'jpi01', 'hhac01', 'Arm hurts after falling','X-Ray', '2021-02-01');
INSERT INTO `mydb`.`Appointments Table` (`Appointment ID`, `Patient ID`, `Username`, `Notes`, `Prescription`, `Dat`) VALUES (3, 'tjo01', 'tje01', '','Omega Tablets', '2021-03-04');
INSERT INTO `mydb`.`Appointments Table` (`Appointment ID`, `Patient ID`, `Username`, `Notes`, `Prescription`, `Dat`) VALUES (4, 'jpi01', 'jsc01', '','Operation', '2021-02-01');

COMMIT;

