# Generated by Django 4.0.2 on 2022-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pred',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_ticker',
            field=models.CharField(max_length=10),
        ),
    ]
